export const ADD_CONTACT = "ADD_CONTACT";
export const EDIT_CONTACT = "EDIT_CONTACT";
export const UPDATE_CONTACT = "UPDATE_CONTACT";
export const DELETE_CONTACT = "DELETE_CONTACT";
export const DELETEALL_CONTACT = "DELETEALL_CONTACT";
export const SELECTALL_CONTACT = "SELECTALL_CONTACT";
export const CLEARALL_CONTACT = "CLEARALL_CONTACT";
export const SELECTONE_CONTACT = "SELECTONE_CONTACT";